
name: linkseq-phase

channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - nextflow=21.04
  - samtools=1.10
  - gatk4=4.1.0.0
  - whatshap=0.18
  - vcftools=0.1
  - perl-vcftools-vcf=0.1
  - pysam=0.16
  - multiqc=1.9
